# kubectl create secret docker-registry registry-credentials --namespace=discord-bot --docker-server=https://registry.gitlab.com --docker-username=$USERNAME --docker-password=$PASSWORD --docker-email=$USEREMAIL
apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: FILE_GENERATED_IN_BASE64_FORMAT
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: discord-bot
type: kubernetes.io/dockerconfigjson
---
# kubectl create secret generic api-secrets
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: discord-bot
data:
  db_pass: VALUE_IN_BASE64_FORMAT
type: Opaque
