# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
variables:
  IMAGE_NAME: discord-roulette-bot
  RUNNER_IMAGE: python:3.10-buster

stages:
- test
- build
- production
- security

run_linting:
  stage: test
  image: ${RUNNER_IMAGE}
  script:
    - pip install black
    - make cicd-lint

run_tests:
  stage: test
  image: ${RUNNER_IMAGE}
  script:
    - make install
    - make test

build_image:
  stage: build
  script:
    - echo "Logging into GitLab container registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Building Docker image..."
    - make build-image IMAGE_NAME=${IMAGE_NAME} IMAGE_TAG=${CI_COMMIT_SHA} .
    - echo "Pushing image to Gitlab container registry..."
    - docker push ${IMAGE_NAME}:${CI_COMMIT_SHA}

sast:
  stage: security

include:
- template: Security/SAST.gitlab-ci.yml
