version: "3.9"

services:
    backend:
        build: .
        ports:
        - "8000:8000"
        env_file:
        - .env
        volumes:
        - "./src:/usr/src/app/src"
        - "./main.py:/usr/src/app/main.py"

    database:
        image: postgres:16.1
        restart: always
        environment:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
        - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4:8.3
        ports:
        - "5050:80"
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
        - "./dev/pgadmin.json:/pgadmin4/servers.json"
        profiles:
        - monitor
