version: "3.9"

services:
    traefik:
        image: traefik:v3.0
        command: --api.insecure=true --providers.docker
        ports:
        - "80:80"
        - "8080:8080"
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        labels:
        - rule = "Host(`traefix.localhost`)"

    api-player:
        build:
          context: .
          dockerfile: environments/dev/Dockerfile.players
        ports:
        - "8001:8000"
        env_file:
        - .env
        volumes:
        - "./api/players:/usr/src"
        depends_on:
        - traefik
        labels:
        - "traefik.http.routers.player.rule=Host(`player.localhost`)"

    api-admin:
        build:
          context: .
          dockerfile: environments/dev/Dockerfile.admin
        ports:
        - "8002:8000"
        env_file:
        - .env
        volumes:
        - "./api/admin:/usr/src"
        depends_on:
        - traefik
        labels:
        - "traefik.http.routers.admin.rule=Host(`admin.localhost`)"

    database:
        image: postgres:16.1
        restart: always
        environment:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
        - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4:8.3
        ports:
        - "5050:80"
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
        - "./environments/dev/pgadmin.json:/pgadmin4/servers.json"
        profiles:
        - monitor
        depends_on:
        - traefik
        labels:
        - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
