version: "3.9"

services:
    player-api:
        build:
          context: .
          dockerfile: environments/dev/Dockerfile.players
        ports:
        - "8001:8000"
        env_file:
        - .env
        volumes:
        - "./src/api/players:/usr/src"

    admin:
        build:
          context: .
          dockerfile: environments/dev/Dockerfile.admin
        ports:
        - "8002:8000"
        env_file:
        - .env
        volumes:
        - "./src/api/admin:/usr/src"

    database:
        image: postgres:16.1
        restart: always
        environment:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
        - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4:8.3
        ports:
        - "5050:80"
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
        - "./environments/dev/pgadmin.json:/pgadmin4/servers.json"
        profiles:
        - monitor
