FROM python:3.11-buster

ENV POETRY_VERSION=1.7.1

WORKDIR /usr/src/app
EXPOSE 8000

RUN pip install "poetry==$POETRY_VERSION"

COPY poetry.lock .
COPY pyproject.toml .
RUN poetry install --no-interaction

COPY src/api/players .
CMD [ "poetry", "run", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]
