FROM python:3.11-buster

ENV POETRY_VERSION=1.7.1

WORKDIR /usr
EXPOSE 8000

RUN pip install "poetry==$POETRY_VERSION"

COPY poetry.lock .
COPY pyproject.toml .
RUN poetry install --no-interaction --no-root

COPY . /usr/src

ENTRYPOINT [ "sleep", "1d"]
